### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nishant87555** [teticio/lambda-scraper#5]
Traceback (most recent call last):
  File "test_scraper.py", line 46, in <module>
    response = proxy.send('https://ipinfo.io/ip')
  File "test_scraper.py", line 37, in get_proxy
    response['body'] = b64decode(response['body'])
  File "/usr/lib64/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by teticio** [comment]
I'm unable to reproduce this. Can you print out response['body'] before the b64decode line?
