### ISSUE TITLE
Function not found: arn:aws:lambda:us-east-1:064598236091:function:proxy-0

### ISSUE THREAD

**Issue by togersonS** [teticio/lambda-scraper#8]
Traceback (most recent call last):
  File "test_scraper.py", line 46, in <module>
    response = proxy.send('https://ipinfo.io/ip')
  File "test_scraper.py", line 29, in get_proxy
    lambda_client.invoke(
  File "/usr/local/python3.8/lib/python3.8/site-packages/botocore/client.py", line 534, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/python3.8/lib/python3.8/site-packages/botocore/client.py", line 976, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-east-1:064598236091:function:proxy-0

**Comment by togersonS** [comment]
region error, still did not fix the other issue.
